# Generated by Django 3.0.3 on 2020-02-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=30)),
                ('id_flux', models.IntegerField(unique=True)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('order_mrid', models.CharField(max_length=20, unique=True)),
                ('order_refid', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
