# Generated by Django 3.0.3 on 2020-03-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200301_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_mrid',
            field=models.CharField(max_length=30),
        ),
    ]
